config/routes.rb
Rails.application.routes.draw do

  devise_for :usuarios
  resources :direccions

  resources :usuarios
root :to => 'inicio#index'
  get 'inicio/index'

end

app/models/direccion.rb
class Direccion < ActiveRecord::Base
  belongs_to :usuario
  validates :calle, presence: true
  validates :numero, presencense: true
  validates :pais, presence: true
  scope :recientes, ->{order("created_at desc")}
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/direccions_controller.rb
class DireccionsController < ApplicationController
  before_action :set_direccion, only: [:show, :edit, :update, :destroy]

  # GET /direccions
  # GET /direccions.json
  def index
    @direccions = Direccion.recientes.all
  end

  # GET /direccions/1
  # GET /direccions/1.json
  def show
  end

  # GET /direccions/new
  def new
    @direccion = Direccion.new
  end

  # GET /direccions/1/edit
  def edit
  end

  # POST /direccions
  # POST /direccions.json
  def create
    @direccion = Direccion.new(direccion_params)

    respond_to do |format|
      if @direccion.save
        format.html { redirect_to @direccion, notice: 'Direccion was successfully created.' }
        format.json { render :show, status: :created, location: @direccion }
      else
        format.html { render :new }
        format.json { render json: @direccion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /direccions/1
  # PATCH/PUT /direccions/1.json
  def update
    respond_to do |format|
      if @direccion.update(direccion_params)
        format.html { redirect_to @direccion, notice: 'Direccion was successfully updated.' }
        format.json { render :show, status: :ok, location: @direccion }
      else
        format.html { render :edit }
        format.json { render json: @direccion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /direccions/1
  # DELETE /direccions/1.json
  def destroy
    @direccion.destroy
    respond_to do |format|
      format.html { redirect_to direccions_url, notice: 'Direccion was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_direccion
      @direccion = Direccion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def direccion_params
      params.require(:direccion).permit(:calle, :numero, :comuna, :ciudad, :pais, :usuario_id)
    end
end

app/controllers/inicio_controller.rb
class InicioController < ApplicationController
  def index
  end
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  before_action :set_usuario, only: [:show, :edit, :update, :destroy]

  # GET /usuarios
  # GET /usuarios.json
  def index
    @usuarios = Usuario.all
  end

  # GET /usuarios/1
  # GET /usuarios/1.json
  def show
  end

  # GET /usuarios/new
  def new
    @usuario = Usuario.new
  end

  # GET /usuarios/1/edit
  def edit
  end

  # POST /usuarios
  # POST /usuarios.json
  def create
    @usuario = Usuario.new(usuario_params)

    respond_to do |format|
      if @usuario.save
        format.html { redirect_to @usuario, notice: 'Usuario was successfully created.' }
        format.json { render :show, status: :created, location: @usuario }
      else
        format.html { render :new }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /usuarios/1
  # PATCH/PUT /usuarios/1.json
  def update
    respond_to do |format|
      if @usuario.update(usuario_params)
        format.html { redirect_to @usuario, notice: 'Usuario was successfully updated.' }
        format.json { render :show, status: :ok, location: @usuario }
      else
        format.html { render :edit }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usuarios/1
  # DELETE /usuarios/1.json
  def destroy
    @usuario.destroy
    respond_to do |format|
      format.html { redirect_to usuarios_url, notice: 'Usuario was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_usuario
      @usuario = Usuario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def usuario_params
      params.require(:usuario).permit(:nombre, :apellido, :fechanacimiento, :correo)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/direccions_helper.rb
module DireccionsHelper
end

app/helpers/inicio_helper.rb
module InicioHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/application/_side.html.erb
<strong>Pages</strong>
<ul>
  <li><%= link_to "Home", root_path %></li>
  <li><%= link_to "Show", usuarios_path %></li>
</ul>

app/views/direccions/_form.html.erb
<%= form_for(@direccion) do |f| %>
  <% if @direccion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@direccion.errors.count, "error") %> prohibited this direccion from being saved:</h2>

      <ul>
      <% @direccion.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :calle %><br>
    <%= f.text_field :calle %>
  </div>
  <div class="field">
    <%= f.label :numero %><br>
    <%= f.number_field :numero %>
  </div>
  <div class="field">
    <%= f.label :comuna %><br>
    <%= f.text_field :comuna %>
  </div>
  <div class="field">
    <%= f.label :ciudad %><br>
    <%= f.text_field :ciudad %>
  </div>
  <div class="field">
    <%= f.label :pais %><br>
    <%= f.text_field :pais %>
  </div>
  <div class="field">
    <%= f.label :usuario_id %><br>
    <%= f.text_field :usuario_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/direccions/edit.html.erb
<h1>Editing direccion</h1>

<%= render 'form' %>

<%= link_to 'Show', @direccion %> |
<%= link_to 'Back', direccions_path %>

app/views/direccions/index.html.erb
<h1>Listing direccions</h1>

<table>
  <thead>
    <tr>
      <th>Calle</th>
      <th>Numero</th>
      <th>Comuna</th>
      <th>Ciudad</th>
      <th>Pais</th>
      <th>Usuario</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @direccions.each do |direccion| %>
      <tr>
        <td><%= direccion.calle %></td>
        <td><%= direccion.numero %></td>
        <td><%= direccion.comuna %></td>
        <td><%= direccion.ciudad %></td>
        <td><%= direccion.pais %></td>
        <td><%= direccion.usuario %></td>
        <td><%= link_to 'Show', direccion %></td>
        <td><%= link_to 'Edit', edit_direccion_path(direccion) %></td>
        <td><%= link_to 'Destroy', direccion, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Direccion', new_direccion_path %>

app/views/direccions/new.html.erb
<h1>New direccion</h1>

<%= render 'form' %>

<%= link_to 'Back', direccions_path %>

app/views/direccions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Calle:</strong>
  <%= @direccion.calle %>
</p>

<p>
  <strong>Numero:</strong>
  <%= @direccion.numero %>
</p>

<p>
  <strong>Comuna:</strong>
  <%= @direccion.comuna %>
</p>

<p>
  <strong>Ciudad:</strong>
  <%= @direccion.ciudad %>
</p>

<p>
  <strong>Pais:</strong>
  <%= @direccion.pais %>
</p>

<p>
  <strong>Usuario:</strong>
  <%= @direccion.usuario %>
</p>

<%= link_to 'Edit', edit_direccion_path(@direccion) %> |
<%= link_to 'Back', direccions_path %>

app/views/inicio/index.html.erb
<h1>Inicio#index</h1>
<p>Find me in app/views/inicio/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">
<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js">
</script>
  <title>Store</title>
  <%= stylesheet_link_tag "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'shared/navbar' %>
  <div id="container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    <% end %>

    <div id="side">
      <%= render "side" %>
    </div>

    <%= yield %>

    <div class="clear"></div>
  </div>
</body>
</html>

app/views/shared/_alert.htm.erb
<% if notice %>
<div class="alert alert-success alert-dismissible" role="alert">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  <%= notice %>
</div>
<% end %>
<% if alert %>
<div class="alert alert-danger alert-dismissible" role="alert">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  <%= alert %>
</div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%=root_path%>">Mi Blog </a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->

    

      <ul class="nav navbar-nav navbar-right">
        <% if usuario_signed_in? %>
        <li><a> <%= current_usuario.email %> </a></li>
        	<li><a href="<%= edit_usuario_registration_path(current_usuario) %>">Editar Perfil</a></li>
        	<li><a href="<%= destroy_usuario_session_path %>", data-method="delete">Cerrar Session</a></li>
        <% else %>
        	<li><a href="<%= new_usuario_session_path %>">Ingresar</a></li>
        	<li><a href="<%= new_usuario_registration_path %>">Registrarse</a></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/usuarios/_form.html.erb
<%= form_for(@usuario) do |f| %>
  <% if @usuario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@usuario.errors.count, "error") %> prohibited this usuario from being saved:</h2>

      <ul>
      <% @usuario.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :apellido %><br>
    <%= f.text_field :apellido %>
  </div>
  <div class="field">
    <%= f.label :fechanacimiento %><br>
    <%= f.date_select :fechanacimiento %>
  </div>
  <div class="field">
    <%= f.label :correo %><br>
    <%= f.text_field :correo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/usuarios/_side.html.erb
<strong>Pages</strong>
<ul>
  <li><%= link_to "Home", root_path %></li>
  <li><%= link_to "show", usuarios_path %></li>
  <li><%= link_to "Manage Products", usuarios_path %></li>
</ul>

app/views/usuarios/edit.html.erb
<h1>Editing usuario</h1>

<%= render 'form' %>

<%= link_to 'Show', @usuario %> |
<%= link_to 'Back', usuarios_path %>

app/views/usuarios/index.html.erb
<h1>Listing usuarios</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Apellido</th>
      <th>Fechanacimiento</th>
      <th>Correo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @usuarios.each do |usuario| %>
      <tr>
        <td><%= usuario.nombre %></td>
        <td><%= usuario.apellido %></td>
        <td><%= usuario.fechanacimiento %></td>
        <td><%= usuario.correo %></td>
        <td><%= link_to 'Show', usuario %></td>
        <td><%= link_to 'Edit', edit_usuario_path(usuario) %></td>
        <td><%= link_to 'Destroy', usuario, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Usuario', new_usuario_path %>

app/views/usuarios/new.html.erb
<h1>New usuario</h1>

<%= render 'form' %>

<%= link_to 'Back', usuarios_path %>

app/views/usuarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @usuario.nombre %>
</p>

<p>
  <strong>Apellido:</strong>
  <%= @usuario.apellido %>
</p>

<p>
  <strong>Fechanacimiento:</strong>
  <%= @usuario.fechanacimiento %>
</p>

<p>
  <strong>Correo:</strong>
  <%= @usuario.correo %>
</p>

<%= link_to 'Edit', edit_usuario_path(@usuario) %> |
<%= link_to 'Back', usuarios_path %>